### ISSUE TITLE
Version Qt_5.9 not found

### ISSUE THREAD

**Issue by dneise** [fact-project/open_crab_sample_analysis#1]
```
(fact) dneise@lair:~/open_crab_sample_analysis$ make
klaas_apply_cuts ./configs/quality_cuts.yaml \
	dl2/proton.hdf5 \
	build/proton_precuts.hdf5 \
	-k events --chunksize=10000
Traceback (most recent call last):
  File "/home/dneise/anaconda36/envs/fact/bin/klaas_apply_cuts", line 11, in <module>
    load_entry_point('klaas==0.7.0', 'console_scripts', 'klaas_apply_cuts')()
  File "/home/dneise/anaconda36/envs/fact/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/dneise/anaconda36/envs/fact/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "/home/dneise/anaconda36/envs/fact/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/home/dneise/anaconda36/envs/fact/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/dneise/anaconda36/envs/fact/lib/python3.6/site-packages/klaas/scripts/apply_cuts.py", line 8, in <module>
    from fact.io import read_data, h5py_get_n_rows
  File "/home/dneise/anaconda36/envs/fact/lib/python3.6/site-packages/fact/__init__.py", line 2, in <module>
    from . import plotting
  File "/home/dneise/anaconda36/envs/fact/lib/python3.6/site-packages/fact/plotting/__init__.py", line 12, in <module>
    from .core import mark_pixel, camera, pixelids
  File "/home/dneise/anaconda36/envs/fact/lib/python3.6/site-packages/fact/plotting/core.py", line 5, in <module>
    import matplotlib.pyplot as plt
  File "/home/dneise/anaconda36/envs/fact/lib/python3.6/site-packages/matplotlib/pyplot.py", line 113, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/home/dneise/anaconda36/envs/fact/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 60, in pylab_setup
    [backend_name], 0)
  File "/home/dneise/anaconda36/envs/fact/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 16, in <module>
    from .backend_qt5 import (
  File "/home/dneise/anaconda36/envs/fact/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 18, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/home/dneise/anaconda36/envs/fact/lib/python3.6/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/home/dneise/anaconda36/envs/fact/lib/python3.6/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 56, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/home/dneise/anaconda36/envs/fact/lib/python3.6/site-packages/matplotlib/backends/qt_compat.py", line 137, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: /home/dneise/anaconda36/envs/fact/bin/../lib/libQt5Core.so.5: version `Qt_5.9' not found (required by /home/dneise/anaconda36/envs/fact/lib/python3.6/site-packages/PyQt5/QtCore.so)
Makefile:65: recipe for target 'build/proton_precuts.hdf5' failed
make: *** [build/proton_precuts.hdf5] Error 1
(fact) dneise@lair:~/open_crab_sample_analysis$ 
```

**Comment by dneise** [comment]
Oh .. that's a local error on my side ... I cannot even start ipython ... I get a SegFault :-{

```
ImportError: /home/dneise/anaconda36/envs/fact/bin/../lib/libQt5Core.so.5: version `Qt_5.9' not found (required by /home/dneise/anaconda36/envs/fact/lib/python3.6/site-packages/PyQt5/QtCore.so)

In [1]: Segmentation fault (core dumped)
```

and in python:
```
(fact) dneise@lair:~/open_crab_sample_analysis$ python
Python 3.6.3 |Anaconda, Inc.| (default, Nov 20 2017, 20:41:42) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot as plt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dneise/anaconda36/envs/fact/lib/python3.6/site-packages/matplotlib/pyplot.py", line 113, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/home/dneise/anaconda36/envs/fact/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 60, in pylab_setup
    [backend_name], 0)
  File "/home/dneise/anaconda36/envs/fact/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 16, in <module>
    from .backend_qt5 import (
  File "/home/dneise/anaconda36/envs/fact/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 18, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/home/dneise/anaconda36/envs/fact/lib/python3.6/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/home/dneise/anaconda36/envs/fact/lib/python3.6/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 56, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/home/dneise/anaconda36/envs/fact/lib/python3.6/site-packages/matplotlib/backends/qt_compat.py", line 137, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: /home/dneise/anaconda36/envs/fact/bin/../lib/libQt5Core.so.5: version `Qt_5.9' not found (required by /home/dneise/anaconda36/envs/fact/lib/python3.6/site-packages/PyQt5/QtCore.so)
```

**Comment by dneise** [comment]
Now sure where this behaviour comes from ... outside the conda environment fact matplotlib works ..

**Comment by dneise** [comment]
Is is most certainly not an issue of this repo, but of my local conda ... so I'll close it
