### ISSUE TITLE
Memory Error 

### ISSUE THREAD

**Issue by kbruegge** [fact-project/open_crab_sample_analysis#2]
This occurs while loading the disp model. Which is weird since its only 88 MB on the file system.

```
kbruegge@phobos:~/open_crab_sample_analysis$ make 
klaas_apply_disp_regressor configs/disp.yaml \
	build/crab_precuts.hdf5 \
	build/disp_model.pkl \
	build/sign_model.pkl \
	-k events  --yes --chunksize=50000
/opt/anaconda3/lib/python3.5/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
INFO:root:Loading model
Traceback (most recent call last):
  File "/home/kbruegge/.local/bin/klaas_apply_disp_regressor", line 11, in <module>
    load_entry_point('klaas==0.7.0', 'console_scripts', 'klaas_apply_disp_regressor')()
  File "/opt/anaconda3/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/kbruegge/.local/lib/python3.5/site-packages/klaas/scripts/apply_disp_regressor.py", line 73, in main
    disp_model = joblib.load(disp_model_path)
  File "/home/kbruegge/.local/lib/python3.5/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 578, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/home/kbruegge/.local/lib/python3.5/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 508, in _unpickle
    obj = unpickler.load()
  File "/opt/anaconda3/lib/python3.5/pickle.py", line 1043, in load
    dispatch[key[0]](self)
  File "/home/kbruegge/.local/lib/python3.5/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 341, in load_build
    self.stack.append(array_wrapper.read(self))
  File "/home/kbruegge/.local/lib/python3.5/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 184, in read
    array = self.read_array(unpickler)
  File "/home/kbruegge/.local/lib/python3.5/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 135, in read_array
    read_size, "array data")
  File "/home/kbruegge/.local/lib/python3.5/site-packages/sklearn/externals/joblib/numpy_pickle_utils.py", line 638, in _read_bytes
    r = fp.read(size - len(data))
  File "/home/kbruegge/.local/lib/python3.5/site-packages/sklearn/externals/joblib/numpy_pickle_utils.py", line 508, in readinto
    return io.BufferedIOBase.readinto(self, b)
  File "/home/kbruegge/.local/lib/python3.5/site-packages/sklearn/externals/joblib/numpy_pickle_utils.py", line 500, in read
    return self._read_block(size)
  File "/home/kbruegge/.local/lib/python3.5/site-packages/sklearn/externals/joblib/numpy_pickle_utils.py", line 473, in _read_block
    while n_bytes > 0 and self._fill_buffer():
  File "/home/kbruegge/.local/lib/python3.5/site-packages/sklearn/externals/joblib/numpy_pickle_utils.py", line 437, in _fill_buffer
    self._buffer = self._decompressor.decompress(rawblock)
MemoryError
Makefile:188: recipe for target 'build/crab_disp_done' failed

```

**Comment by maxnoe** [comment]
I cannot reproduce this
